### ISSUE TITLE
Map not displayed

### ISSUE THREAD

**Issue by IagoLast** [CartoDB/tangram-carto#55]
Regarding to this map:

https://mamataakella.carto.com/builder/e623bb0c-b2fd-11e5-b55f-0ea31932ec1d/embed

After some research, I found that is something related to the marker-size.

The following includes the 2 scene.yaml files that can be tested in the tangram.play https://gist.github.com/IagoLast/a0c085c71db4e43829f733f60d84caad , notice that the original size property `layers>hash>data>draw` causes tangram to crash.

### EDIT 1

I found **2 bugs** in tangram-carto

#### Default value bug
There is a [helper function](https://github.com/CartoDB/tangram-carto/blob/master/src/utils/utils.js#L17) in tangram-carto which creates aux functions for variable sizes/colors..etc

This helper function sets the [default value to null](https://github.com/CartoDB/tangram-carto/blob/master/src/utils/utils.js#L21), generating problems when the value is not overwritten.
In the case of this map, for the color, we have the following:

```javascript
function() {
  var _value = null; // Default value --> null
  if ((63 & (1 << $zoom)) && feature['outbreaks'] >= 500) {
    _value = feature['symbol_size'];
  }
  if ((8 & (1 << $zoom)) && feature['outbreaks'] >= 500) {
    _value = feature['symbol_size'] * 2;
  }
  if ((16 & (1 << $zoom)) && feature['outbreaks'] >= 500) {
    _value = feature['symbol_size'] * 4;
  }
  return _value; // Sometimes this function returns null causing a tangram error!
}
```

#### Colide bug
Acording to the [tangram doc](https://mapzen.com/documentation/tangram/draw/#collide) must be a boolean field.

Tangran-carto gets the `collide` value from the [getCollide(c3ss)](https://github.com/CartoDB/tangram-carto/blob/master/src/basic/points.js#L114).

In the case of this map, this function returns 0 instead "true" so the map is not looking well.

As long as I know the getCollide (which value for this map must be **false**, gets the value from the `maker-allow-overlap` field in the cartocss which now has the following value:

```json
{
  "constant": true,
  "symbolizer": "markers",
  "js": [
    "if((63 & (1 << ctx.zoom)) && data['outbreaks'] >= 500){_value = true;}"
  ],
  "index": 285
}
```

cc @alonsogarciapablo @rochoa

**Comment by IagoLast** [comment]
The bug 1 can be fixed changing the default value from **null** to 0. (and praying).

I need more context to solve the bug 2.

**Comment by alonsogarciapablo** [comment]
Great job investigating this @IagoLast !

**Comment by IagoLast** [comment]
Forget about the collide bug. Its a consequence of changing the default value.

If the default value remains to "null" there´s no problem so mi previous proposal of changing the default value from null to 0 is discarded.

**Comment by IagoLast** [comment]
## Final report.

The are 2 bugs here, one related to the `marker-with` default value and another one related to `marker-allow-overlap` property.

### Bug1: Marker with default value

In the attached map, the cartocss is the following:

```less
#layer_name [outbreaks >= 500][zoom <= 5]{
  marker-fill-opacity: 0.5;
  marker-line-color: #FFF;
  marker-line-width: 0.25;
  marker-line-opacity: 1;
  marker-fill: #fff;
  marker-allow-overlap: true;
  marker-width: [symbol_size]; // <---

  [zoom = 3]{
    marker-width:[symbol_size] * 2;
  }
...
```
As you can see, marker-with is only set when `outbreaks >= 500` and `zoom <= 5` causing the error explained in the [edit1](https://github.com/CartoDB/tangram-carto/issues/55#issue-249318370)

IMO an issue should be created in order to give the right default value in the size function.


### Bug 2: marker-allow-overlap
According to the [tangram-doc](https://mapzen.com/documentation/tangram/draw/#collide) collide must be a **BOOLEAN** field, this means that no functions can be used here.

Again, if we check the css we can see that the `marker-allow-overlap` rule is depends on the zoom and the outbreaks values. This mean that at tangram-css level will be translated to a function that tangram will ignore.

IMO: The fix for this would be a fallback to raster when allow-overlap is included under a conditional rule. and ask tangram to support functions in the collide field.


#### Note: This two bugs dissapear with little modifications in the cartocss:

```less
#layer_name {
  marker-width: [symbol_size]; // We give a default value for this
  marker-allow-overlap: true;  // Allow overlap is not conditional anymore!
  
  [outbreaks >= 500][zoom <= 5]{
    marker-fill-opacity: 0.5;
    marker-line-width: 0.25;


  }

  [ zoom = 3] {
      marker-width:[symbol_size] * 2;
  }

```

The vector result can be checked [here](https://team.carto.com/u/iago-carto/builder/78ef5f8a-27e6-47c9-9c8b-51ef539a529e/embed?vector=true)

cc @rochoa @alonsogarciapablo
